version: '3'

services:
  java:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  front:
    build:
      context: courier_administration
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  node:
    build:
      context: express-app
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - db
